# Generated by Django 5.2.3 on 2025-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Введите название заголовка",
                        max_length=50,
                        verbose_name="Название заголовка",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Описание содержимого контента",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото продукта",
                        null=True,
                        upload_to="blogs_image/",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "number_of_views",
                    models.IntegerField(verbose_name="Количество просмотров"),
                ),
            ],
            options={
                "verbose_name": "<Блог>",
                "verbose_name_plural": "Блоги",
                "ordering": ["heading", "content"],
            },
        ),
    ]
